spring:
  application:
    name: complaint-manager

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5433/complaintmanager}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: ${FLYWAY_DB_USER:admin}
    password: ${FLYWAY_DB_PASSWORD:admin}


geolocation:
  url: "https://ipapi.co"
  connectionTimeout: "1000"
  readTimeout: "15000"